#!/usr/bin/env python3
"""PreToolUse hook: refuse edits to the generated API client."""

import json
import sys

GENERATED = "frontend/apps/web/src/client/"

payload = json.load(sys.stdin)
path = str(payload.get("tool_input", {}).get("file_path", "")).replace("\\", "/")

if GENERATED in path:
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": (
                        f"{GENERATED} is generated by Hey API and is overwritten on "
                        "every regeneration. Change the backend route or model, then "
                        "run `bash scripts/generate-client.sh`."
                    ),
                }
            }
        )
    )
