apiVersion: v1
kind: Service
metadata:
  name: {{ include "connexity.frontend.serviceName" . }}
  labels:
    {{- include "connexity.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "connexity.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
