"""checks: findings, decision records, and when each check first existed

Revision ID: 0008_check_engine
Revises: 0007_executions_checked_at
Create Date: 2026-10-10 13:00:08.947859

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0008_check_engine'
down_revision = '0007_executions_checked_at'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_release',
    sa.Column('check_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('check_type', 'version')
    )
    op.create_table('decision_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('check_setting', name='decisionkind', native_enum=False, length=32), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_by_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_record_agent_id'), 'decision_record', ['agent_id'], unique=False)
    op.create_index('ix_decision_record_agent_kind_subject', 'decision_record', ['agent_id', 'kind', 'subject'], unique=False)
    op.create_index(op.f('ix_decision_record_company_id'), 'decision_record', ['company_id'], unique=False)
    op.create_index(op.f('ix_decision_record_created_at'), 'decision_record', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_record_decided_by'), 'decision_record', ['decided_by'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('check_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('check_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('rule', 'classifier', 'judge', name='checkkind', native_enum=False, length=32), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('event_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detail', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('effect', sa.Enum('flags', 'fails', name='findingeffect', native_enum=False, length=32), nullable=False),
    sa.Column('retroactive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_agent_id'), 'finding', ['agent_id'], unique=False)
    op.create_index('ix_finding_agent_type_key', 'finding', ['agent_id', 'check_type', 'key'], unique=False)
    op.create_index(op.f('ix_finding_call_id'), 'finding', ['call_id'], unique=False)
    op.create_index(op.f('ix_finding_company_id'), 'finding', ['company_id'], unique=False)
    op.add_column('call', sa.Column('checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call', 'checked_at')
    op.drop_index(op.f('ix_finding_company_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_call_id'), table_name='finding')
    op.drop_index('ix_finding_agent_type_key', table_name='finding')
    op.drop_index(op.f('ix_finding_agent_id'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_decision_record_decided_by'), table_name='decision_record')
    op.drop_index(op.f('ix_decision_record_created_at'), table_name='decision_record')
    op.drop_index(op.f('ix_decision_record_company_id'), table_name='decision_record')
    op.drop_index('ix_decision_record_agent_kind_subject', table_name='decision_record')
    op.drop_index(op.f('ix_decision_record_agent_id'), table_name='decision_record')
    op.drop_table('decision_record')
    op.drop_table('check_release')
    # ### end Alembic commands ###
